impl_lib: AAAAA_OUTDRIVER
root_dir: data/aib_out_driver
env_list: ['tt_25']

digital_db_files:
  stack2_config_file:
    - specs_digital_char/aib/digitalDB_specs_lvl_stack2.yaml
    - [nmos]
  stack1_config_file:
    - specs_digital_char/aib/digitalDB_specs_lvl_stack1.yaml
    - [pmos, nmos]
  stdgates_pupd_file:
    - specs_digital_char/aib/stdgates_pupd.yaml
    - [pmos, nmos]

dsn_params:
  output:
    rout: 70
    rout_weak: 20e3
  input:
    cout: 20.0e-15
    freq: 2e9
    vdd_io: 1.0
    vdd_core: 0.8
    lch: 36
    nfin_min: 1
    pfin_min: 1
    nseg_min: 1
    pseg_min: 1
    nfin_max: 4
    pfin_max: 4

    nand_nor_fanout: 4
    rel_trf_matching: 0.05